name: My First Workflow

on:
  manual_trigger:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "Hello Sanjai"
      - name: Check Linux Version
        run: uname -a
      - name: master
        run: free -h ; nproc ; date

